name: Radio Roasters Coffee
favicon: null
layout_spectrum: 0.40058
typography_spectrum: 0.32143
title: Radio Roasters Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e0e'
    - '#f2f2f2'
    - '#444444'
    - '#767676'
    - '#969696'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.6170986271463335
  rhythmicContrast: 0.5
purpose: []
