name: Radio Roasters Coffee
favicon: null
layout_spectrum: 0.9894178246613592
typography_spectrum: 0.5938885784707963
title: Radio Roasters Coffee
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0e0e'
    - '#f2f2f2'
    - '#444444'
    - '#767676'
    - '#969696'
  brandStrength: 0.3790320851840079
  lightness: 0.15009427373297513
  saturation: 0.6170986271463335
  rhythmicContrast: 0.23608615482226014
purpose: []
